name: Build and Release SwiftUI Component

on:
  push:
    tags:
      - '*'  # Corre cuando se crea cualquier tag (ej: v1.0.0)

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build XCFramework
        run: |
          SCHEME="AlertComponent"
          FRAMEWORK_NAME="AlertComponentDemo"
          ARCHIVE_DIR="archives"
          XCFRAMEWORK_OUTPUT="$FRAMEWORK_NAME.xcframework"

          rm -rf "$ARCHIVE_DIR" "$XCFRAMEWORK_OUTPUT"

          xcodebuild archive \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_DIR/ios_devices" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            clean archive

          xcodebuild archive \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            -archivePath "$ARCHIVE_DIR/ios_simulators" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            clean archive

          xcodebuild -create-xcframework \
            -framework "$ARCHIVE_DIR/ios_devices.xcarchive/Products/Library/Frameworks/$FRAMEWORK_NAME.framework" \
            -framework "$ARCHIVE_DIR/ios_simulators.xcarchive/Products/Library/Frameworks/$FRAMEWORK_NAME.framework" \
            -output "$XCFRAMEWORK_OUTPUT"

      - name: Compress XCFramework
        run: |
          zip -r MyComponent.xcframework.zip MyComponent.xcframework

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MyComponent.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
